version: '2.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=testing
      - POSTGRES_DB=packages
      - PGDATA=/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data

  flaskmigration:
    build: .
    image: quiltdata/flask
    environment:
      - AWS_ACCESS_KEY_ID=ddccbbaa
      - AWS_SECRET_ACCESS_KEY=abcd
      - QUILT_SERVER_CONFIG=docker_config.py
      - STRIPE_SECRET_KEY=STRIPETEST
      - REGISTRY_URL=http://$DEPLOY_URL:5000
      - CATALOG_URL=http://$DEPLOY_URL:3000
      - S3_ENDPOINT_URL=http://$DEPLOY_URL:5001
      - QUILT_SECRET_KEY=deadbeef
      - ALLOW_ANONYMOUS_ACCESS=True
    depends_on:
      db:
        condition: service_healthy
    command:
      flask db upgrade

  flask:
    build: .
    image: quiltdata/flask
    environment:
      - AWS_ACCESS_KEY_ID=ddccbbaa
      - AWS_SECRET_ACCESS_KEY=abcd
      - QUILT_SERVER_CONFIG=docker_config.py
      - AUTH_PROVIDER=quilt
      - DEPLOYMENT_ID=dev
      - REGISTRY_URL=http://$DEPLOY_URL:5000
      - CATALOG_URL=http://$DEPLOY_URL:3000
      - S3_ENDPOINT_URL=http://$DEPLOY_URL:5001
      - QUILT_SECRET_KEY=deadbeef
      - ALLOW_ANONYMOUS_ACCESS=True
    depends_on:
      db:
        condition: service_healthy

  nginxflask:
    image: nginx:latest
    ports:
      - "5000:80"
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx-quilt.conf:/etc/nginx/nginx-quilt.template
    environment:
      - UWSGI_HOST=flask
      - UWSGI_PORT=9000
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/nginx-quilt.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  s3:
    build: nginx-s3
    image: quiltdata/nginx-s3-proxy
    ports:
      - "5001:5001"

  catalog:
    build: ../catalog
    image: quiltdata/catalog
    environment:
      - REGISTRY_URL=http://$DEPLOY_URL:5000
      - STRIPE_KEY=NOSTRIPE
    ports:
      - "3000:80"
